<!DOCTYPE html>
<html lang="en">

<head>

<?php if (array_key_exists('analytics-id', $content['header'])) : ?>
	<!--Google Analytics-->
	<script>
	(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
	(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
	m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
	})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');
	
	ga('create', '<?php echo $content['header']['analytics-id']?>', 'auto');
	ga('send', 'pageview');
	</script>
	<!--/Google Analytics-->
<?php endif;?>

	<title><?php echo $context->localize($content['header']['title'], $locale) ?></title>
	<meta charset="utf-8">
	<meta name="description" content="<?php echo $context->localize($content['header']['description'], $locale) ?>">
	<meta name="robots" content="index, follow">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta http-equiv="x-ua-compatible" content="ie=edge">

	<!-- Font Awesome -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">    <!-- Bootstrap core CSS -->
	<link href="<?php echo $this->basePath('MDB-Pro/css/bootstrap.min.css" rel="stylesheet') ?>">

	<!-- Material Design Bootstrap -->
	<link href="<?php echo $this->basePath('MDB-Pro/css/mdb.min.css" rel="stylesheet') ?>">
	<link href="<?php echo $this->basePath('MDB-Pro/css/style.css" rel="stylesheet') ?>">
	
	<!-- medium editor -->
	<link rel="stylesheet" href="<?php echo $this->basePath('medium-editor-master/dist/css/medium-editor.css') ?>">
	<link rel="stylesheet" href="<?php echo $this->basePath('medium-editor-master/dist/css/themes/default.css" id="medium-editor-theme') ?>">
	
	<!-- jquery-ui -->
	<link href="<?php echo $this->basePath('jquery-ui-1.12.1/jquery-ui.min.css" rel="stylesheet') ?>">

    <!-- Custom styles -->
	<style>
	html,
	body,
	header,
	#intro {
	  height: 100%;
	}
	
	#intro {
	  background: url("<?php echo $this->basePath($context->localize($content['header']['background_image']['src'], $locale)) ?>")no-repeat center center fixed;
	  -webkit-background-size: cover;
	  -moz-background-size: cover;
	  -o-background-size: cover;
	  background-size: cover;
	}
	
	@include media-breakpoint-up(sm) {
	  html {
	    font-size: 16px;
	  }
	}
	
	@include media-breakpoint-up(md) {
	  html {
	    font-size: 20px;
	  }
	}
	
	@include media-breakpoint-up(lg) {
	  html {
	    font-size: 28px;
	  }
	}
	
	.portlet {
	  margin: 0 1em 1em 0;
	  padding: 0.3em;
	}
	.portlet-header {
	  padding: 0.2em 0.3em;
	  margin-bottom: 0.5em;
	  position: relative;
	}
	.portlet-toggle {
	  position: absolute;
	  top: 50%;
	  right: 0;
	  margin-top: -8px;
	}
	.portlet-content {
	  padding: 0.4em;
	}
	.portlet-placeholder {
	  border: 1px dotted black;
	  margin: 0 1em 1em 0;
	  height: 50px;
	}
	
	.resizable { font-size: 16px; text-align: center; margin: 0; }
	</style>
</head>

<body>

  <!--Main Navigation-->
  <header>

    <!-- Sign in and registration -->
    <?php echo $this->partial('/partials/navbar.phtml'); ?>
 
    <!-- Mask -->
    <div id="intro" class="view h-100"> 
      <div class="d-block h-100 w-lg-100 <?php echo $content['header']['background_image']['mask'] ?>">
        <div class="full-bg-img flex-center">
          <div class="col-md-12 justify-content-center text-center">
<?php foreach ($content['intro'] as $paragraphId => $paragraph) : ?>

  <?php if (array_key_exists('a', $paragraph)) : ?>
            <a
              href="<?php echo $this->url('landing/template2') ?><?php echo $paragraph['a']['href']?>"
    <?php if (array_key_exists('class', $paragraph['a'])) echo 'class="'.$paragraph['a']['class'].'"' ?>
    <?php if (array_key_exists('id', $paragraph['a'])) echo 'id="'.$paragraph['a']['id'].'"' ?>
            >

  <?php elseif (array_key_exists('button', $paragraph)) : ?>
            <button type="button" 
    <?php if (array_key_exists('class', $paragraph['button'])) echo 'class="'.$paragraph['button']['class'].'"' ?>
    <?php if (array_key_exists('id', $paragraph['button'])) echo 'id="'.$paragraph['button']['id'].'"' ?>
            >

  <?php else : ?>
            <<?php echo $paragraph['type']?> class="editable <?php if (array_key_exists('class', $paragraph)) echo $paragraph['class'] ?>" id="<?php echo $paragraphId ?>/text<?php if (array_key_exists('text', $paragraph)) echo '/'.$context->getLocaleFor($paragraph['text']) ?>">
  <?php endif;?>
  
  <?php if (array_key_exists('text', $paragraph)) : ?>
            <?php echo $context->localize($paragraph['text'], $locale) ?>
  <?php endif;?>

  <?php if (array_key_exists('a', $paragraph)) : ?>
            </a>
  <?php elseif (array_key_exists('button', $paragraph)) : ?>
            </button>
  <?php else : ?>
            </<?php echo $paragraph['type']?>>
  <?php endif;?>
<?php endforeach;?>
          </div>
        </div>
      </div>
    </div>
    <!--/Mask-->

  </header>
  <!--/Main Navigation-->

  <!--Main layout-->
  <main>  
    <div class="container" name="descr" id="descr">
      <br><br><br>
 
 <?php foreach ($content['presentation'] as $section) : ?>

        <!-- Presentation section -->
        <div class="presentation-section">

          <div class="portlet-header">
            <ul class="nav grey lighten-4">
              <li class="nav-item">
                <a class="nav-link text-secondary"><i class="fa fa-edit"></i></a>
              </li>
              <li>
                <a class="nav-link text-secondary"><i class="fa fa-trash"></i></a>
              </li>
            </ul>
          </div>

          <div class="portlet-content">
  
  <?php if ($section['type'] == 'lightbox') : ?>
            <!--Section: Blog v.4-->
            <section class="section section-blog-fw mt-5 pb-3 wow fadeIn">
              <div id="mdb-lightbox-ui"></div>
              <div class="mdb-lightbox <?php if (array_key_exists('margin', $section) && !$section['margin']) echo 'no-margin' ?>">
                <div class="view overlay">

  <?php elseif ($section['type'] == 'feature-box') : ?>
            <section class="section feature-box wow fadeIn" data-wow-delay="0.3s">

  <?php elseif ($section['type'] == 'card-cascade') : ?>
            <section class="section wow fadeIn" data-wow-delay="0.3s">
              <!--Featured image-->
              <div class="card card-cascade wider reverse">
                <div class="view view-cascade overlay">
  <?php endif;?>
	
  <?php foreach ($section['rows'] as $row) : ?>
                  <div class="row">

    <?php foreach ($row as $column) : ?>
                    <figure class="<?php echo $column['column-class']?>">
                      <div class="resizable ui-widget-content">
                        <span class="ui-widget-header">Drag for resizing</span>
                      </div>
                      <<?php echo $column['type']?> class="<?php if (array_key_exists('class', $column)) echo $column['class'] ?>">

      <?php if (array_key_exists('a', $column)) : ?>
                      <a 
        <?php foreach ($column['a'] as $attrId => $attr) : ?>
          <?php if ($attrId == 'href') : ?>
                        <?php echo $attrId ?>="<?php echo $this->basePath($attr) ?>"
          <?php else : ?>
                        <?php echo $attrId ?>="<?php echo $attr ?>"
          <?php endif;?>
        <?php endforeach;?>
                      >

      <?php elseif (array_key_exists('button', $column)) : ?>
                      <button type="button" 
                        <?php if (array_key_exists('class', $column['button'])) echo 'class="'.$column['button']['class'].'"' ?>
                        <?php if (array_key_exists('id', $column['button'])) echo 'id="'.$column['button']['id'].'"' ?>
                      >

      <?php endif;?>

      <?php if (array_key_exists('text', $column)) : ?>
                      <?php echo $context->localize($column['text'], $locale) ?>

      <?php elseif (array_key_exists('img', $column)) : ?>
                      <img 
        <?php foreach ($column['img'] as $attrId => $attr) : ?>
          <?php if ($attrId == 'src') : ?>
                        <?php echo $attrId ?>="<?php echo $this->basePath($attr) ?>"
          <?php else : ?>
                        <?php echo $attrId ?>="<?php echo $attr ?>"
          <?php endif;?>
        <?php endforeach;?>
                      />

      <?php endif;?>

      <?php if (array_key_exists('a', $column)) : ?>
                      </a>
      <?php elseif (array_key_exists('button', $column)) : ?>
                      </button>
      <?php endif;?>
                      </<?php echo $column['type']?>>
                    </figure>
    <?php endforeach;?>
                  </div>
  <?php endforeach;?>

  <?php if ($section['type'] == 'lightbox') : ?>
                </div>
              </div>
            </section>
	
  <?php elseif ($section['type'] == 'feature-box') : ?>
            </section>

  <?php elseif ($section['type'] == 'card-cascade') : ?>
                </div>
              </div>
            </section>

  <?php endif;?>

          </div>
        </div>
        <!--/ Presentation section -->

<?php endforeach;?>

      <!-- Contact Form -->	
      <section class="section pb-5 wow fadeIn" data-wow-delay="0.3s" id="survey">
        <div class="row">

<?php foreach ($content['form']['introduction'] as $paragraph) : ?>
  <?php if (array_key_exists('a', $paragraph)) : ?>
          <a 
            href="<?php echo $paragraph['a']['href']?>" 
          	<?php if (array_key_exists('class', $paragraph['a'])) echo 'class="'.$paragraph['a']['class'].'"' ?>
          	<?php if (array_key_exists('id', $paragraph['a'])) echo 'id="'.$paragraph['a']['id'].'"' ?>
          >

  <?php elseif (array_key_exists('button', $paragraph)) : ?>
          <button type="button" 
          	<?php if (array_key_exists('class', $paragraph['button'])) echo 'class="'.$paragraph['button']['class'].'"' ?>
          	<?php if (array_key_exists('id', $paragraph['button'])) echo 'id="'.$paragraph['button']['id'].'"' ?>
          >
		
  <?php else : ?>
          <<?php echo $paragraph['type']?> <?php if (array_key_exists('class', $paragraph)) echo 'class="'.$paragraph['class'].'"' ?>>

  <?php endif;?>

  <?php if (array_key_exists('text', $paragraph)) : ?>
          <?php echo $context->localize($paragraph['text'], $locale) ?>
  
  <?php endif;?>
	
  <?php if (array_key_exists('a', $paragraph)) : ?>
          </a>

  <?php elseif (array_key_exists('button', $paragraph)) : ?>
          </button>

  <?php else : ?>
          </<?php echo $paragraph['type']?>>
		
  <?php endif;?>
<?php endforeach;?>

        </div>
        <hr>
        <div class="row">

          <!--Grid column-->
          <div class="col-md-8 col-xl-9">
            <form action="<?php echo $this->url('landing/template2', array('place_identifier' => $place_identifier, 'id' => $id)) ?>?hash=<?php echo $token ?>#survey" method="post">
              <div class="row">

 <?php foreach ($content['form']['inputs'] as $inputId => $property) : ?>
                <?php $disabled = $message || $error || $id && !$property['updatable'] ?>
                <div class="<?php echo (array_key_exists('class',$property)) ? $property['class'] : 'col-md-6' ?>">
                  <div class="md-form">

  <?php if ($property['type'] == 'select') : ?>
                    <select id="<?php echo $inputId ?>" name="<?php echo $inputId ?>" class="mdb-select validate" <?php if ($property['mandatory']) echo 'required="required"' ?> <?php if ($disabled) echo 'disabled="disabled"' ?>>
                      <option value=""><?php echo $this->translate('Please choose', 'ppit-core', $context->getLocale()) ?></option>
    <?php foreach ($property['modalities'] as $modalityId => $modality) : ?>
                      <option value="<?php echo $modalityId ?>" <?php if ($viewData[$inputId] == $modalityId) echo 'selected="selected"' ?>><?php echo $context->localize($modality, $locale) ?></option>
    <?php endforeach;?>
                    </select>
                    <label for="<?php echo $inputId ?>" class=""><?php if ($property['mandatory']) echo '* ' ?><?php echo $context->localize($property['labels'], $locale) ?></label>

  <?php elseif ($property['type'] == 'radio') : ?>
                    <input type="radio" id="<?php echo $inputId ?>" name="<?php echo $property['property_id'] ?>" class="form-control validate with-gap" value="<?php echo $property['value'] ?>" <?php if ($disabled) echo 'disabled="disabled"' ?> <?php if ($viewData[$inputId]) echo 'checked="checked"' ?> />
                    <label for="<?php echo $inputId ?>" class=""><?php if ($property['mandatory']) echo '* ' ?><?php echo $context->localize($property['labels'], $locale) ?></label>

  <?php elseif ($property['type'] == 'checkbox') : ?>
                    <input type="checkbox" id="<?php echo $inputId ?>" name="<?php echo $inputId ?>" class="form-check-input validate" value="<?php echo $property['value'] ?>" <?php if ($disabled) echo 'disabled="disabled"' ?> <?php if ($viewData[$inputId]) echo 'checked="checked"' ?> />
                    <label for="<?php echo $inputId ?>" class="form-check-label"><?php if ($property['mandatory']) echo '* ' ?><?php echo $context->localize($property['labels'], $locale) ?></label>

  <?php elseif ($property['type'] == 'textarea') : ?>
                    <textarea rows="<?php echo $property['rows'] ?>" id="<?php echo $inputId ?>" name="<?php echo $inputId ?>" class="md-textarea form-control validate" <?php if ($property['placeholder']) echo 'placeholder="'.$context->localize($property['placeholder'], $locale).'"' ?> <?php if ($property['mandatory']) echo 'required="required"' ?> <?php if ($disabled) echo 'disabled="disabled"' ?>><?php echo $viewData[$inputId] ?></textarea>
                    <label for="<?php echo $inputId ?>" class=""><?php if ($property['mandatory']) echo '* ' ?><?php echo $context->localize($property['labels'], $locale) ?></label>

  <?php elseif ($property['type'] == 'file') : ?>
                    <div class="file-field">
                      <div class="btn btn-primary btn-sm float-left ">
                        <span><?php if ($property['mandatory']) echo '* ' ?><?php echo $this->translate('Choose file', 'ppit-core', $context->getLocale()) ?></span>
                        <input type="file" id="<?php $inputId ?>" name="<?php echo $inputId ?>" class="form-control validate" <?php if ($property['mandatory']) echo 'required="required"' ?> <?php if ($disabled) echo 'disabled="disabled"' ?> value=" value="<?php echo $viewData[$inputId] ?>">
                      </div>
                      <div class="file-path-wrapper">
                        <input class="file-path validate" type="text" placeholder="<?php echo $context->localize($property['labels'], $locale) ?>" >
                      </div>
                    </div>

  <?php elseif ($property['type'] == 'email') : ?>
                    <input type="email" id="<?php echo $inputId ?>" name="<?php echo $inputId ?>" class="form-control validate" <?php if ($property['placeholder']) echo 'placeholder="'.$context->localize($property['placeholder'], $locale).'"' ?> <?php if ($property['mandatory']) echo 'required="required"' ?> <?php if ($disabled) echo 'disabled="disabled"' ?> value="<?php echo $viewData[$inputId] ?>" />
                    <label for="<?php echo $inputId ?>" class=""><?php if ($property['mandatory']) echo '* ' ?><?php echo $context->localize($property['labels'], $locale) ?></label>

  <?php elseif ($property['type'] == 'input') : ?>
                    <input type="text" id="<?php echo $inputId ?>" name="<?php echo $inputId ?>" class="form-control validate" <?php if ($property['placeholder']) echo 'placeholder="'.$context->localize($property['placeholder'], $locale).'"' ?> <?php if ($property['mandatory']) echo 'required="required"' ?> <?php if ($disabled) echo 'disabled="disabled"' ?> value="<?php echo $viewData[$inputId] ?>" />
                    <label for="<?php echo $inputId ?>" class=""><?php if ($property['mandatory']) echo '* ' ?><?php echo $context->localize($property['labels'], $locale) ?></label>

  <?php elseif ($property['type'] == 'separation') : ?>
                    <hr>

  <?php else : ?>
                    <span class="font-weight-bold"><?php echo $context->localize($property['labels'], $locale) ?></span>

  <?php endif;?>
                  </div>
                </div>

<?php endforeach;?>

              </div>

<?php if ($message || $error) : ?>
              <p class="section-description">
                <a href="<?php echo $this->url('home') ?>" class="btn btn-light-blue btn-rounded">Accueil</a>
              </p>

<?php else : ?>
              <div class="center-on-small-only">
                <button class="btn btn-light-blue btn-rounded" type="submit"><?php echo $context->localize($content['form']['submit']['labels'], $locale) ?></button>
              </div>

<?php endif;?>

            </form>
          </div>
          <!--Grid column-->

<?php if (array_key_exists('contact_section', $content)) : ?>
          <!--Grid column-->
          <div class="col-md-4 col-xl-3">
            <ul class="contact-icons text-center list-unstyled">

  <?php if (array_key_exists('location', $content['contact_section'])) : ?>
              <li><i class="fa fa-map-marker fa-2x"></i>
                <p><?php echo $context->localize($content['contact_section']['location']['label'], $locale) ?></p>
              </li>
  <?php endif;?>

  <?php if (array_key_exists('phone', $content['contact_section'])) : ?>
              <li><i class="fa fa-phone fa-2x"></i>
                <p><?php echo $context->localize($content['contact_section']['phone']['label'], $locale) ?></p>
              </li>
  <?php endif;?>

  <?php if (array_key_exists('email', $content['contact_section'])) : ?>
              <li><i class="fa fa-envelope fa-2x"></i>
                <p><?php echo $context->localize($content['contact_section']['email']['label'], $locale) ?></p>
              </li>
  <?php endif;?>

            </ul>
          </div>
          <!--Grid column-->

<?php endif;?>

        </div>
      </section> 
      <!--/ Contact form -->

    </div>

    <!--Footer-->
    <footer class="page-footer indigo lighten-3 pt-4 mt-4 text-center text-md-left mt-5">

      <!--Footer Links-->
      <div class="container">
        <div class="row">

          <!--First column-->
          <div class="col-md-3">
            <h5 class="title">Ressources </h5>
            <ul class="list-unstyled">
              <li>
	           <a data-toggle="modal" data-target="#modalShowCharterForm"><?php echo $this->translate('Charter', 'ppit-core', $context->getLocale()) ?></a>
              </li>
            </ul>
          </div>
          <!--/First column-->

          <hr class="w-100 clearfix d-md-none">

          <!--Second column-->
          <div class="col-md-2 ml-auto">
            <ul class="list-unstyled">
              <li><a href="#!"></a></li>
            </ul>
          </div>
          <!--/Second column-->

        </div>
      </div>

      <!--Copyright-->
      <div class="footer-copyright py-3 text-center">
        <div class="container-fluid">
          © 2018 Copyright: <a href="https://github.com/2pit-io/PpitCore/blob/master/license.txt"> 2pit.io </a>
        </div>
      </div>
      <!--/Copyright-->

    </footer>
    <!--/ Footer -->
  
<div class="modal fade" id="modalShowCharterForm" tabindex="-1" role="dialog" aria-labelledby="modalShowCharterLabel" aria-hidden="true">
    <div class="modal-dialog modal-lg" role="document">
        <div class="modal-content">
              <div class="modal-header text-center">
                  <h4 class="modal-title w-100 font-weight-bold"></h4>
                  <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                      <span aria-hidden="true">&times;</span>
                  </button>
              </div>
              <div class="modal-body mx-3">
                  <div id="show_charter_content"></div>
              </div>
              <div class="modal-footer d-flex justify-content-center">
		        <button type="button" class="btn btn-link" data-dismiss="modal" aria-label="Close">
		          <?php echo $this->translate('Close', 'ppit-core', $context->getLocale()) ?>
		        </button>
              </div>
        </div>
    </div>
</div>

  </main>
</body>
    	
<!-- SCRIPTS -->
<!-- Font Awesome -->
<!-- JQuery -->
<script type="text/javascript" src="<?php echo $this->basePath('MDB-Pro/js/jquery-3.3.1.min.js') ?>"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript" src="<?php echo $this->basePath('MDB-Pro/js/popper.min.js') ?>"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript" src="<?php echo $this->basePath('MDB-Pro/js/bootstrap.min.js') ?>"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript" src="<?php echo $this->basePath('MDB-Pro/js/mdb.min.js') ?>"></script>

<script type="text/javascript">
// Material Select Initialization
new WOW().init();
$(document).ready(function() {
   $('.mdb-select').material_select();
});

//MDB Lightbox Init
$(function () {
  $("#mdb-lightbox-ui").load("<?php echo $this->basePath('MDB-Pro/mdb-addons/mdb-lightbox-ui.html') ?>");
});

//Google Analytics
<?php if ($message) : ?>
ga('send', 'event', '<?php echo (array_key_exists('campaign', $content['header'])) ? $content['header']['campaign'] : $place_identifier ?>', 'submit', 'landing_template2#survey', 1);
<?php endif;?>

$('#a_survey').click(function () {
<?php if (array_key_exists('analytics-id', $content['header'])) : ?>
  ga('send', 'event', '<?php echo (array_key_exists('campaign', $content['header'])) ? $content['header']['campaign'] : $place_identifier ?>', 'click', 'landing_template2#survey', 1);
<?php endif;?>
  $(location).attr('href', '#descr');
});

<?php if ($message) : ?>
toastr.success('<?php echo $this->translate('Your request has been registered', 'ppit-core', $context->getLocale()) ?>');
<?php elseif ($error) : ?>
toastr.error('<?php echo $this->translate('Technical information: ', 'ppit-core', $context->getLocale()).$error[0] ?>');
toastr.error('<?php echo $this->translate('An error has occurred, please try again later', 'ppit-core', $context->getLocale()) ?>');
<?php endif ?>

$('.portlet-header').hide();
$('.resizable').hide();
</script>

<?php if ($context->hasRole('admin')) : ?>
<!-- Updatable landing page for authorized users -->

<!-- Medium editor -->
<script src="<?php echo $this->basePath('medium-editor-master/dist/js/medium-editor.js') ?>"></script>
<script>
  //Returns a function, that, as long as it continues to be invoked, will not
  //be triggered. The function will be called after it stops being called for
  //N milliseconds. If `immediate` is passed, trigger the function on the
  //leading edge, instead of the trailing.
  function debounce(func, wait, immediate) {
    var timeout;
    return function() {
    var context = this, args = arguments;
    var later = function() {
      timeout = null;
      if (!immediate) func.apply(context, args);
    };
    var callNow = immediate && !timeout;
      clearTimeout(timeout);
      timeout = setTimeout(later, wait);
      if (callNow) func.apply(context, args);
    };
  };
  var editor = new MediumEditor('.editable', {
    buttonLabels: 'fontawesome'
  });
  function triggerAutoSave(event, editable) {
    var xhttp = new XMLHttpRequest();
    xhttp.open("POST", '<?php echo $this->url('config/v1', ['identifier' => $place_identifier.'_landing']) ?>', true);
    xhttp.onreadystatechange = function() {
      if (xhttp.readyState == 4 && xhttp.status == 200) {
      }
    }
    var content = { content: {} };
    content.content['intro/' + editable.id] = editable.innerHTML;
    xhttp.send(JSON.stringify(content));
  }
  var throttledAutoSave = debounce(triggerAutoSave, 1000);
  editor.subscribe('editableInput', throttledAutoSave);
</script>
<!--/ medium editor -->

<!-- jqueryui: sortable portlets -->
<script src="<?php echo $this->basePath('jquery-ui-1.12.1/jquery-ui.js') ?>"></script>
<script>
$( function() {
  $( ".column" ).sortable({
    connectWith: ".column",
    handle: ".portlet-header",
    cancel: ".portlet-toggle",
    placeholder: "portlet-placeholder ui-corner-all ui-state-highlight"
  });
   
  $( ".portlet" )
    .addClass( "ui-widget ui-widget-content ui-helper-clearfix ui-corner-all" )
    .find( ".portlet-header" )
    .addClass( "ui-widget-header ui-corner-all" )
    .prepend( "<span class='ui-icon ui-icon-minusthick portlet-toggle'></span>");

  $( ".portlet-toggle" ).on( "click", function() {
    var icon = $( this );
    icon.toggleClass( "ui-icon-minusthick ui-icon-plusthick" );
    icon.closest( ".portlet" ).find( ".portlet-content" ).toggle();
  });
} );
$('.presentation-section').addClass('portlet');
$('.portlet-header').show();
</script>
<!--/ jqueryui: sortable portlets -->

<!--/ jqueryui: resizable -->
<script>
$( function() {
  var currentWidth;
  $( ".resizable" ).resizable({
    maxWidth: 600,
//    handles: "e",
    create: function( event, ui ) {
      var classAttr = $(this).parent().attr('class'), pos = classAttr.search('col-');
      var nbCols = parseInt(classAttr.substring(pos+7));
      $(this).css('width', nbCols*50 + 'px');
      currentWidth = nbCols*50;
    },
    resize: function( event, ui ) {
      if (ui.size.width % 50 == 0) {
        $(this).parent().removeClass('col-md-1');
        $(this).parent().removeClass('col-md-2');
        $(this).parent().removeClass('col-md-3');
        $(this).parent().removeClass('col-md-4');
        $(this).parent().removeClass('col-md-5');
        $(this).parent().removeClass('col-md-6');
        $(this).parent().removeClass('col-md-7');
        $(this).parent().removeClass('col-md-8');
        $(this).parent().removeClass('col-md-9');
        $(this).parent().removeClass('col-md-10');
        $(this).parent().removeClass('col-md-11');
        $(this).parent().removeClass('col-md-12');
        $(this).parent().addClass('col-md-' + ui.size.width / 50);
        currentWidth = ui.size.width;
        console.log(currentWidth / 50);
      }
    }
  });
} );
$('.resizable').show();
</script>
<!--/ jqueryui: resizable -->

<!--/ Updatable landing page for authorized users -->
<?php endif;?>

<!-- Sign in and registration -->
<?php echo $this->partial('/partials/navbar-script.phtml'); ?>

<script>
$('#modalShowCharterForm').on('show.bs.modal', function () { 
    var xhttp = new XMLHttpRequest();
    xhttp.open('GET', '<?php echo $this->url('instance/charter') ?>', true);
    xhttp.onload = function () {
      if (xhttp.readyState == 4 && xhttp.status == 200) $('#show_charter_content').html(xhttp.responseText);
      else toastr.error("<?php echo $this->translate('A technical error has occured. PLease try again later', 'ppit-core', $context->getLocale()) ?>");
    };
    xhttp.send();
});
</script>

</html>
