<!DOCTYPE html>
<html lang="en">

<!-- Header -->
<?php echo $this->partial('/partials/flow-header') ?>

<div class="container" id="main">
	<section class="section pb-5 wow fadeIn" data-wow-delay="0.3s">
		<div>&nbsp;</div>
		<div class="row public-text">
			<div class="col-md-4">
				<div class="view overlay hm-white-light z-depth-1-half">
					<img src="<?php echo $this->basePath($content['image']['src']) ?>" <?php if (array_key_exists('class', $content['image'])) echo 'class="'.$content['image']['class'].'"' ?> if (array_key_exists('alt', $paragraph)) alt="<?php echo $content['image']['alt'] ?>" />
					<div class="mask"></div>
				</div>
			</div>
		
			<div class="col-md-8" id="document_part_panel_0">			
				<div class="card-block">
<?php foreach ($content['text'] as $paragraph) : ?>
					<<?php echo $paragraph['type']?> <?php if (array_key_exists('class', $paragraph)) echo 'class="'.$paragraph['class'].'"' ?>>
	<?php if (array_key_exists('text', $paragraph)) : ?>
		<?php foreach ($paragraph['text'] as $segment) : ?>
						<<?php echo $segment['type']?> <?php if (array_key_exists('class', $segment)) echo 'class="'.$segment['class'].'"' ?>>
		<?php if (array_key_exists('a', $segment)) : ?>
							<a 
								href="<?php echo $segment['a']['href']?>" 
								<?php if (array_key_exists('class', $segment['a'])) echo 'class="'.$segment['a']['class'].'"' ?>
								<?php if (array_key_exists('id', $segment['a'])) echo 'id="'.$segment['a']['id'].'"' ?>
							>
		<?php endif;?>
							<?php if (array_key_exists('text', $segment)) echo $segment['text'] ?>
		<?php if (array_key_exists('a', $segment)) : ?>
							</a>
		<?php endif;?>
						</<?php echo $segment['type']?>>
		<?php endforeach;?>
					</<?php echo $paragraph['type']?>>
	<?php endif;?>
<?php endforeach;?>
				</div>
	        </div>
		</div>
	</section>
	
	<section class="section pb-5 wow fadeIn" data-wow-delay="0.3s" id="form">
		<h2 class="section-heading h1 pt-4" id="survey">Participer au sondage</h2>
		<p class="section-description">
			Génial ! Nous vous remercions et serons heureux de vous accueillir dans la communauté.<br>
			Nous vous invitons à répondre à ces quatre questions simples et anonymes.
		</p>
		<div class="row">
			
			<!--Grid column-->
			<div class="col-md-8 col-xl-9">
				<form>
					<div class="row">
						<div class="col-md-12">
							<div class="md-form">
								<input type="text" id="contact-name" class="form-control">
								<label for="contact-name" class="">Les compétences que je pourrais proposer/demander</label>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div class="md-form">
								<input type="text" id="contact-name" class="form-control">
								<label for="contact-name" class="">Le temps que je pourrais consacrer à donner un coup de main</label>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div class="md-form">
								<textarea id="contact-message" class="md-textarea"></textarea>
								<label for="contact-message">Les freins pour utiliser la plateforme pour demander de l’aide / pour proposer ses compétences</label>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div class="md-form">
								<textarea id="contact-message" class="md-textarea"></textarea>
								<label for="contact-message">Ce qu’il faudrait éviter de faire avec cette plateforme</label>
							</div>
						</div>
					</div>
					<div class="row">
						<div class="col-md-12">
							<div class="md-form">
								<textarea id="contact-message" class="md-textarea"></textarea>
								<label for="contact-message">Commentaire libre</label>
							</div>
						</div>
					</div>
				</form>
				<div class="center-on-small-only">
					<a class="btn btn-light-blue btn-rounded">Soumettre</a>
				</div>
			</div>
			<!--Grid column-->

			<!--Grid column-->
			<div class="col-md-4 col-xl-3">
				<ul class="contact-icons">
					<li><i class="fa fa-map-marker fa-2x"></i>
						<p>Paris La Défense, France</p>
					</li>
					<li><i class="fa fa-phone fa-2x"></i>
						<p>01 02 03 04 05</p>
					</li>
					<li><i class="fa fa-envelope fa-2x"></i>
						<p>contact-probono@socgen.com</p>
					</li>
				</ul>
			</div>
			<!--Grid column-->
		</div>
	</section> 
	<!--Section: Contact v.2-->

</div>

<!-- Footer -->
<?php echo $this->partial('/partials/flow-footer') ?>

<script>
$('#form').hide();
$('#a_survey').click(function() { $('#form').show() });
</script>

</html>
