<!DOCTYPE html>
<html lang="en">

<head>
<?php if (array_key_exists('analytics-id', $content['header'])) : ?>
<!-- Google Analytics -->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', '<?php echo $content['header']['analytics-id']?>', 'auto');
ga('send', 'pageview');
</script>
<!-- End Google Analytics -->
<?php endif;?>

    <title><?php echo $context->localize($content['header']['title'], $locale) ?></title>
    <meta charset="utf-8">
	<meta name="description" content="<?php echo $context->localize($content['header']['description'], $locale) ?>">
	<meta name="robots" content="index, follow">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <!-- Font Awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">    <!-- Bootstrap core CSS -->
    <link href="<?php echo $this->basePath('MDB-Pro/css/bootstrap.min.css" rel="stylesheet') ?>">
    <!-- Material Design Bootstrap -->
    <link href="<?php echo $this->basePath('MDB-Pro/css/mdb.min.css" rel="stylesheet') ?>">
    <!-- Your custom styles (optional) -->
    <link href="<?php echo $this->basePath('MDB-Pro/css/style.css" rel="stylesheet') ?>">

    <link rel="stylesheet" href="<?php echo $this->basePath('medium-editor-master/dist/css/medium-editor.css') ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('medium-editor-master/dist/css/themes/default.css" id="medium-editor-theme') ?>">

<style>
html,
body,
header,
#intro {
    height: 70%;
}

#intro {
    background: url("<?php echo $this->basePath($content['header']['background_image']['src']) ?>") no-repeat ;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
}

@include media-breakpoint-up(sm) {
  html {
    font-size: 16px;
  }
}

@include media-breakpoint-up(md) {
  html {
    font-size: 20px;
  }
}

@include media-breakpoint-up(lg) {
  html {
    font-size: 28px;
  }
}
</style>
</head>

<body>

    <!--Main Navigation-->
    <header>

<?php echo $this->partial('/partials/navbar.phtml'); ?>

<!--Mask-->
<div id="intro" class="view h-100"> 
	<div class="d-block h-100 w-lg-100 <?php echo $content['header']['background_image']['mask'] ?>">
    	<div class="full-bg-img flex-center">
            <div class="col-md-12 justify-content-center text-center">
	        </div>
        </div>
    </div>
</div>
<!--/.Mask-->
            
    </header>
    <!--Main Navigation-->

    <!--Main layout-->
    <main>
<form action="<?php echo $this->url('request/fill', ['id' => $id]) ?>?locale=<?php echo $locale ?>" method="post">
<div class="container" name="descr" id="descr">
	<br>
	<section class="section feature-box wow fadeIn" data-wow-delay="0.3s">
<?php if ($id) : ?>
      <h3 class="font-weight-bold text-center h3 my-5"><?php echo $this->translate('View/update a request', 'ppit-core', $context->getLocale()) ?></h3>
<?php else : ?>
      <h3 class="font-weight-bold text-center h3 my-5"><?php echo $this->translate('Submit a new request', 'ppit-core', $context->getLocale()) ?></h3>
<?php endif;?>
   	</section>

	<section class="section pb-5 wow fadeIn" data-wow-delay="0.3s">

		<!--Grid column-->
		<div class="col-md-12">
	
			<div class="row">
<?php foreach ($content['form']['introduction'] as $paragraph) : ?>
	<?php if (array_key_exists('a', $paragraph)) : ?>
				<a 
					href="<?php echo $paragraph['a']['href']?>" 
					<?php if (array_key_exists('class', $paragraph['a'])) echo 'class="'.$paragraph['a']['class'].'"' ?>
					<?php if (array_key_exists('id', $paragraph['a'])) echo 'id="'.$paragraph['a']['id'].'"' ?>
				>
	<?php elseif (array_key_exists('button', $paragraph)) : ?>
				<button type="button" 
					<?php if (array_key_exists('class', $paragraph['button'])) echo 'class="'.$paragraph['button']['class'].'"' ?>
					<?php if (array_key_exists('id', $paragraph['button'])) echo 'id="'.$paragraph['button']['id'].'"' ?>
				>
	<?php else : ?>
				<<?php echo $paragraph['type']?> <?php if (array_key_exists('class', $paragraph)) echo 'class="'.$paragraph['class'].'"' ?>>
	<?php endif;?>
	<?php if (array_key_exists('text', $paragraph)) : ?>
				<?php echo $context->localize($paragraph['text'], $locale) ?>
	<?php endif;?>
	<?php if (array_key_exists('a', $paragraph)) : ?>
				</a>
	<?php elseif (array_key_exists('button', $paragraph)) : ?>
				</button>
	<?php else : ?>
				</<?php echo $paragraph['type']?>>
	<?php endif;?>
<?php endforeach;?>
			</div>

			<div class="row">
<?php if ($content['form']['options']['examples']) : ?>
				<div class="col-md-6">&nbsp;</div>
				<div class="col-md-6"><a class="btn btn-secondary btn-sm" id="other-example"><?php echo $this->translate('Other example', 'ppit-flow', $locale) ?></a></div>
<?php endif;?>

 <?php foreach ($content['form']['inputs'] as $inputId => $property) : ?>
 	<?php $disabled = $message || $error || $id && !$property['updatable'] ?>
				<div class="<?php echo (array_key_exists('class',$property)) ? $property['class'] : 'col-md-6' ?>">
					<div class="md-form">

				<?php if ($property['type'] == 'select') : ?>
						<select id="<?php echo $inputId ?>" name="<?php echo $inputId ?>" class="mdb-select validate" <?php if ($property['mandatory']) echo 'required="required"' ?> <?php if ($disabled) echo 'disabled="disabled"' ?>>
							<option value=""><?php echo $this->translate('Please choose', 'ppit-core', $context->getLocale()) ?></option>
					<?php foreach ($property['modalities'] as $modalityId => $modality) : ?>
							<option value="<?php echo $modalityId ?>" <?php if ($viewData[$inputId] == $modalityId) echo 'selected="selected"' ?>><?php echo $context->localize($modality, $locale) ?></option>
					<?php endforeach;?>
						</select>
						<label for="<?php echo $inputId ?>" class=""><?php if ($property['mandatory']) echo '* ' ?><?php echo $context->localize($property['labels'], $locale) ?></label>

     			<?php elseif ($property['type'] == 'radio') : ?>
						<input type="radio" id="<?php echo $inputId ?>" name="<?php echo $property['property_id'] ?>" class="form-control validate with-gap" value="<?php echo $property['value'] ?>" <?php if ($disabled) echo 'disabled="disabled"' ?> <?php if ($viewData[$inputId]) echo 'checked="checked"' ?> />
						<label for="<?php echo $inputId ?>" class=""><?php if ($property['mandatory']) echo '* ' ?><?php echo $context->localize($property['labels'], $locale) ?></label>

     			<?php elseif ($property['type'] == 'checkbox') : ?>
						<input type="checkbox" id="<?php echo $inputId ?>" name="<?php echo $inputId ?>" class="form-control validate" value="<?php echo $property['value'] ?>" <?php if ($disabled) echo 'disabled="disabled"' ?> <?php if ($viewData[$inputId]) echo 'checked="checked"' ?> />
						<label for="<?php echo $inputId ?>" class=""><?php if ($property['mandatory']) echo '* ' ?><?php echo $context->localize($property['labels'], $locale) ?></label>

				<?php elseif ($property['type'] == 'textarea') : ?>
						<textarea rows="<?php echo $property['rows']?>" id="<?php echo $inputId ?>" name="<?php echo $inputId ?>" class="form-control validate" <?php if ($property['placeholder']) echo 'placeholder="'.$context->localize($property['placeholder'], $locale).'"' ?> <?php if ($property['mandatory']) echo 'required="required"' ?> <?php if ($disabled) echo 'disabled="disabled"' ?>><?php echo $viewData[$inputId] ?></textarea>
						<label for="<?php echo $inputId ?>" class=""><?php if ($property['mandatory']) echo '* ' ?><?php echo $context->localize($property['labels'], $locale) ?></label>

				<?php elseif ($property['type'] == 'file') : ?>
						<div class="file-field">
							<div class="btn btn-primary btn-sm float-left ">
								<span><?php if ($property['mandatory']) echo '* ' ?><?php echo $this->translate('Choose file', 'ppit-core', $context->getLocale()) ?></span>
								<input type="file" id="<?php $inputId ?>" name="<?php echo $inputId ?>" class="form-control validate" <?php if ($property['mandatory']) echo 'required="required"' ?> <?php if ($disabled) echo 'disabled="disabled"' ?> value=" value="<?php echo $viewData[$inputId] ?>">
							</div>
							<div class="file-path-wrapper">
								<input class="file-path validate" type="text" placeholder="<?php echo $context->localize($property['labels'], $locale) ?>" >
							</div>
						</div>

     			<?php elseif ($property['type'] == 'email') : ?>
						<input type="email" id="<?php echo $inputId ?>" name="<?php echo $inputId ?>" class="form-control validate" <?php if ($property['placeholder']) echo 'placeholder="'.$context->localize($property['placeholder'], $locale).'"' ?> <?php if ($property['mandatory']) echo 'required="required"' ?> <?php if ($disabled) echo 'disabled="disabled"' ?> value="<?php echo $viewData[$inputId] ?>" />
						<label for="<?php echo $inputId ?>" class=""><?php if ($property['mandatory']) echo '* ' ?><?php echo $context->localize($property['labels'], $locale) ?></label>

     			<?php elseif ($property['type'] == 'keywords') : ?>
						<input type="text" id="<?php echo $inputId ?>" name="<?php echo $inputId ?>" class="form-control mdb-autocomplete" <?php if ($property['placeholder']) echo 'placeholder="'.$context->localize($property['placeholder'], $locale).'"' ?> <?php if ($property['mandatory']) echo 'required="required"' ?> <?php if ($disabled) echo 'disabled="disabled"' ?> value="<?php echo $viewData[$inputId] ?>">
						<label for="<?php echo $inputId ?>" class=""><?php if ($property['mandatory']) echo '* ' ?><?php echo $context->localize($property['labels'], $locale) ?></label>

     			<?php elseif ($property['type'] == 'date') : ?>
						<input type="text" id="<?php echo $inputId ?>" name="<?php echo $inputId ?>" class="form-control datepicker" <?php if ($property['placeholder']) echo 'placeholder="'.$context->localize($property['placeholder'], $locale).'"' ?> <?php if ($property['mandatory']) echo 'required="required"' ?> <?php if ($disabled) echo 'disabled="disabled"' ?> value="<?php echo $context->decodeDate($viewData[$inputId]) ?>" />
						<label for="<?php echo $inputId ?>" class=""><?php if ($property['mandatory']) echo '* ' ?><?php echo $context->localize($property['labels'], $locale) ?></label>

     			<?php elseif ($property['type'] == 'time') : ?>
						<input type="text" id="<?php echo $inputId ?>" name="<?php echo $inputId ?>" class="form-control timepicker" <?php if ($property['placeholder']) echo 'placeholder="'.$context->localize($property['placeholder'], $locale).'"' ?> <?php if ($property['mandatory']) echo 'required="required"' ?> <?php if ($disabled) echo 'disabled="disabled"' ?> value="<?php echo $viewData[$inputId] ?>" />
						<label for="<?php echo $inputId ?>" class=""><?php if ($property['mandatory']) echo '* ' ?><?php echo $context->localize($property['labels'], $locale) ?></label>

     			<?php elseif ($property['type'] == 'input') : ?>
						<input type="text" id="<?php echo $inputId ?>" name="<?php echo $inputId ?>" class="form-control validate" <?php if ($property['placeholder']) echo 'placeholder="'.$context->localize($property['placeholder'], $locale).'"' ?> <?php if ($property['mandatory']) echo 'required="required"' ?> <?php if ($disabled) echo 'disabled="disabled"' ?> value="<?php echo $viewData[$inputId] ?>" />
						<label for="<?php echo $inputId ?>" class=""><?php if ($property['mandatory']) echo '* ' ?><?php echo $context->localize($property['labels'], $locale) ?></label>

     			<?php elseif ($property['type'] == 'separation') : ?>
     					<hr>

     			<?php elseif ($property['type'] == 'chips') : ?>
					<?php $currentSkills = explode(',', $viewData[$inputId]) ?>
			        	<div class="text-center">
					<?php foreach ($property['repository'] as $entryId => $entry) : ?>
							<input type="hidden" id="<?php echo $inputId.'-'.$entryId ?>" name="<?php echo $inputId.'-'.$entryId ?>" value="<?php echo in_array($entryId, $currentSkills) ? 1 : 0 ?>" />
							<span id="search-<?php echo $inputId ?>-<?php echo $entryId ?>" class="chip <?php echo $entry['color'] ?> white-text search-<?php echo $inputId ?> <?php if (!in_array($entryId, $currentSkills)) echo 'search-'.$inputId.'-hidden' ?>">
								<?php echo $context->localize($entry['labels'], $locale) ?>
                      <?php if (!$disabled) : ?>
							    &nbsp;<a><i id="chip-<?php echo $inputId ?>-<?php echo $entryId ?>" class="search-<?php echo $inputId ?>-close fa fa-times" style="color: red"></i></a>
                      <?php endif;?>
							</span>
					<?php endforeach;?>
						</div>

     			<?php else : ?>
						<span id='<?php echo $inputId ?>'></span>

				<?php endif;?>
					</div>
				</div>
<?php endforeach;?>
			</div>

			<div class="row">

				<div class="center-on-small-only">
<?php if (!$message && !$error) : ?>
					<button class="btn btn-secondary btn-rounded" type="submit"><?php echo $context->localize($content['form']['submit']['labels'], $locale) ?></button>&nbsp;&nbsp;
<?php endif;?>
                    <a href="<?php echo $this->url('profile/template1') ?>" class=""><?php echo $this->translate('Return to list', 'ppit-core', $context->getLocale()) ?></a>
				</div>
			</div>
	    </div>
		<!--Grid column-->
	</section> 

	<section class="section pb-5 wow fadeIn" data-wow-delay="0.3s">
		<br>
		<div class="row">
<?php foreach ($content['form']['legal'] as $paragraph) : ?>
		<?php if (array_key_exists('a', $paragraph)) : ?>
					<a 
						href="<?php echo $paragraph['a']['href']?>" 
						<?php if (array_key_exists('class', $paragraph['a'])) echo 'class="'.$paragraph['a']['class'].'"' ?>
						<?php if (array_key_exists('id', $paragraph['a'])) echo 'id="'.$paragraph['a']['id'].'"' ?>
					>
		<?php elseif (array_key_exists('button', $paragraph)) : ?>
					<button type="button" 
						<?php if (array_key_exists('class', $paragraph['button'])) echo 'class="'.$paragraph['button']['class'].'"' ?>
						<?php if (array_key_exists('id', $paragraph['button'])) echo 'id="'.$paragraph['button']['id'].'"' ?>
					>
		<?php else : ?>
					<<?php echo $paragraph['type']?> <?php if (array_key_exists('class', $paragraph)) echo 'class="'.$paragraph['class'].'"' ?>>
		<?php endif;?>
		<?php if (array_key_exists('text', $paragraph)) : ?>
			<?php echo $context->localize($paragraph['text'], $locale) ?>
		<?php endif;?>
		<?php if (array_key_exists('a', $paragraph)) : ?>
					</a>
		<?php elseif (array_key_exists('button', $paragraph)) : ?>
					</button>
		<?php else : ?>
					</<?php echo $paragraph['type']?>>
		<?php endif;?>
<?php endforeach;?>
		</div>
	</section> 

	</div>
</form>

   <!--Footer-->
    <footer class="page-footer center-on-small-only mt-5">

        <!--Footer Links-->
        <div class="container">
            <div class="row">

                <!--First column-->
                <div class="col-md-3">
                    <h5 class="title">Ressources </h5>
                </div>
                <!--/.First column-->

                <hr class="w-100 clearfix d-md-none">

                <!--Second column-->
                <div class="col-md-2 ml-auto">
                    <ul>
                        <li><a href="#!">Blog</a></li>
                    </ul>
                </div>
                <!--/.Second column-->

            </div>
        </div>

        <!--Copyright-->
        <div class="footer-copyright">
            <div class="container-fluid">
                © 2018 Copyright: <a href="http://www.flowux.io"> Flow UX </a>

            </div>
        </div>
        <!--/.Copyright-->

    </footer>
    </main>
    <!--Main layout-->
</body>
    	
    <!-- SCRIPTS -->
    <!-- Font Awesome -->
    <!-- JQuery -->
    <script type="text/javascript" src="<?php echo $this->basePath('MDB-Pro/js/jquery-3.3.1.min.js') ?>"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="<?php echo $this->basePath('MDB-Pro/js/popper.min.js') ?>"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="<?php echo $this->basePath('MDB-Pro/js/bootstrap.min.js') ?>"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="<?php echo $this->basePath('MDB-Pro/js/mdb.min.js') ?>"></script>

<script type="text/javascript">
// Material Select Initialization
new WOW().init();
$(document).ready(function() {
   $('.mdb-select').material_select();
});

<?php if ($message && array_key_exists('analytics', $content['header'])) : ?>
ga('send', 'event', '<?php echo (array_key_exists('campaign', $content['header'])) ? $content['header']['campaign'] : $place_identifier ?>', 'submit', 'landing_template2#survey', 1);
<?php endif;?>

$('#a_survey').click(function () {
<?php if (array_key_exists('analytics', $content['header'])) : ?>
	ga('send', 'event', '<?php echo (array_key_exists('campaign', $content['header'])) ? $content['header']['campaign'] : $place_identifier ?>', 'click', 'landing_template2#survey', 1);
<?php endif;?>
	$(location).attr('href', '#descr');
});

<?php if ($error) : ?>
toastr.error('<?php echo $this->translate('Technical information: ', 'ppit-core', $context->getLocale()).$error ?>');
toastr.error('<?php echo $this->translate('An error has occurred, please try again later', 'ppit-core', $context->getLocale()) ?>');
<?php endif;?>

$('.datepicker').pickadate({
	monthsFull: ['Janvier', 'Février', 'Mars', 'Avril', 'Mai', 'Juin', 'Juillet', 'Août', 'Septembre', 'Octobre', 'Novembre', 'Décembre'],
	weekdaysShort: ['Dim', 'Lun', 'Mar', 'Mer', 'Jeu', 'Ven', 'Sam'],
	today: 'aujourd\'hui',
	clear: 'effacer',
	format: 'dd/mm/yyyy',
	formatSubmit: 'yyyy-mm-dd'
});
$('.timepicker').pickatime({});

</script>
<?php //if ($context->hasRole('sales_manager')) : ?>
<script src="<?php echo $this->basePath('medium-editor-master/dist/js/medium-editor.js') ?>"></script>
<script>
	//Returns a function, that, as long as it continues to be invoked, will not
	//be triggered. The function will be called after it stops being called for
	//N milliseconds. If `immediate` is passed, trigger the function on the
	//leading edge, instead of the trailing.
	function debounce(func, wait, immediate) {
		var timeout;
		return function() {
			var context = this, args = arguments;
			var later = function() {
				timeout = null;
				if (!immediate) func.apply(context, args);
			};
			var callNow = immediate && !timeout;
			clearTimeout(timeout);
			timeout = setTimeout(later, wait);
			if (callNow) func.apply(context, args);
		};
	};
	var editor = new MediumEditor('.editable', {
        buttonLabels: 'fontawesome'
    });
    function triggerAutoSave(event, editable) {
    	var xhttp = new XMLHttpRequest();
    	xhttp.open("POST", '<?php echo $this->url('config/v1', ['id' => $id.'_profile']) ?>', true);
    	xhttp.onreadystatechange = function() {
    		if (xhttp.readyState == 4 && xhttp.status == 200) {
    		}
    	}
        var content = { content: {} };
        content.content['intro/' + editable.id] = editable.innerHTML;
    	xhttp.send(JSON.stringify(content));
    }
    var throttledAutoSave = debounce(triggerAutoSave, 1000);
    editor.subscribe('editableInput', throttledAutoSave);

// Submit the form

<?php foreach ($content['form']['inputs'] as $inputId => $property) : ?>
	<?php if ($property['type'] == 'chips') : ?>
	var <?php echo $inputId ?> = {
	<?php $first = true; foreach ($property['repository'] as $entryId => $entry) : ?>
	<?php 
	if (!$first) echo ',';
	$first = false;
	 ?>
	 	"<?php echo $entryId ?>": "<?php echo $context->localize($entry['labels'], $locale) ?>"
	<?php endforeach;?>
	};

    $('.search-<?php echo $inputId ?>-hidden').hide();

    $('#<?php echo $property['trigger'] ?>').mdb_autocomplete({
        data: <?php echo $inputId ?>
    });

    $('#<?php echo $property['trigger'] ?>').change(function () {
        var matched;
        setTimeout(function () {
	        for (id in <?php echo $inputId ?>) {
	        	if (<?php echo $inputId ?>[id] == $('#<?php echo $property['trigger'] ?>').val()) {
		        	$('#<?php echo $inputId ?>-' + id).val(1);
		        	$('#search-<?php echo $inputId ?>-' + id).show();
		        	$('#<?php echo $property['trigger'] ?>').val('');
		        	break;
	        	}
	        }
        }, 600);
    });

    $('.search-<?php echo $inputId ?>-close').click(function () {
	<?php foreach ($property['repository'] as $entryId => $entry) : ?>
    	if ($(this).attr('id').split('-')[2] == '<?php echo $entryId ?>') $('#<?php echo $inputId ?>-<?php echo $entryId ?>').val(0);
	<?php endforeach;?>
    	$(this).parent().parent().hide();
    });
    <?php endif;?>
<?php endforeach;?>

<?php if ($message) : ?>
toastr.success('<?php echo $this->translate('Your request has been registered', 'ppit-core', $context->getLocale()) ?>');
<?php endif;?>

//Tooltips Initialization
$(function () {
  $('[data-toggle="tooltip"]').tooltip()
})

<?php foreach ($content['tooltips'] as $itemId => $tooltip) : ?>
$('#<?php echo $itemId ?>').attr('data-toggle', 'tooltip');
$('#<?php echo $itemId ?>').addClass('red-tooltip');
$('#<?php echo $itemId ?>').attr('data-placement', '<?php echo (array_key_exists('data-placement', $tooltip)) ? $tooltip['data-placement'] : 'right' ?>');
$('#<?php echo $itemId ?>').attr('title', '<?php echo $context->localize($tooltip['title'], $locale) ?>');
	<?php if (array_key_exists('data-html', $tooltip)) : ?>
$('#<?php echo $itemId ?>').attr('data-html', true);
	<?php endif;?>
<?php endforeach;?>

<?php if ($content['form']['options']['examples']) : ?>
var example = 0;

function loadExample(number) {
<?php foreach ($content['examples'] as $number => $example) : ?>
	if (number == <?php echo $number ?>) {
	<?php foreach ($example as $propertyId => $labels) : ?>
		$('#<?php echo $propertyId ?>').html('<?php echo $context->localize($labels) ?>');
	<?php endforeach;?>
	}
<?php endforeach;?>
}

loadExample(example);
$('#other-example').click(function () { 
	example = (example + 1) % <?php echo count($content['examples']) ?>;
	loadExample(example); 
});
<?php endif;?>
</script>

<?php echo $this->partial('/partials/navbar-script.phtml'); ?>

</html>
