
<!--Card-->
<div class="card card-cascade narrower">

    <!--Card header-->
    <div class="view py-3 gradient-card-header info-color-dark mx-4 d-flex justify-content-between align-items-center">

  <div>
  </div>

  <a href="" class="white-text mx-3"><?php echo $this->translate('My requests', 'ppit-core', $context->getLocale()) ?></a>

  <div>
  </div>

    </div>
    <!--/Card header-->

    <!--Card content-->
    <div class="card-body">

      <div class="table-responsive" id="table_list">
<?php 
$properties = $content['description']['properties'];
?>
<table class="table">
    <thead>
        <tr>
<?php foreach ($content['description']['list'] as $propertyId => $options) : ?>
	<?php $property = $properties[$propertyId] ?>
            <th class="th-lg"><?php echo $context->localize($property['labels']) ?></th>
<?php endforeach;?>
        </tr>
    </thead>
    <tbody>
<?php foreach ($content['data'] as $item) : ?>
        <tr>

	<?php foreach ($content['description']['list'] as $propertyId => $options) : ?>
		<?php $property = $properties[$propertyId] ?>

		<?php if ($property['type'] == 'select') : ?>
            <td><?php if ($item[$propertyId]) echo $context->localize($properties[$propertyId]['modalities'][$item[$propertyId]]) ?></td>

		<?php elseif ($property['type'] == 'date') : ?>
            <td><?php echo $context->decodeDate($item[$propertyId]) ?></td>

		<?php elseif ($property['type'] == 'number') : ?>
            <td><?php echo $context->formatNumber($item[$propertyId], 2) ?></td>

		<?php else : ?>
            <td><?php echo $item[$propertyId] ?></td>

        <?php endif;?>
	<?php endforeach;?>
        </tr>
<?php endforeach ?>
    </tbody>
</table>
      </div>
      <div class="center-on-small-only">
		<a href="<?php echo $this->url('survey/newRequest') ?>" class="btn btn-light-blue btn-rounded"><?php echo $this->translate('Nouvelle demande', 'ppit-flow', $context->getLocale()) ?></a>
	  </div>
      
</div>
<!--Bottom Table UI-->

    </div>
    <!--/.Card content-->

</div>
<!--/.Card-->
