<script>

 // Upload the photo
 $('#photo_upload').change(function () {
 	var formData = new FormData();
 	var fileSelect = document.getElementById('photo_path');
 	if (fileSelect) {
 		var files = fileSelect.files;
 		for (var i = 0; i < files.length; i++) {
 			var file = files[i];
 			formData.append('photo_path', file, file.name);
 		}
 	}

 	var xhttp = new XMLHttpRequest();
 	xhttp = new XMLHttpRequest();
 	xhttp.open("POST", '<?php echo $this->url('profile/photoUpload', ['id' => $account_id]) ?>', true);
 	xhttp.onreadystatechange = function() {
 		if (xhttp.status == 401) location.href = '<?php echo $this->url('user/expired')?>';
 		if (xhttp.readyState == 4 && xhttp.status == 200) {
 			$('#photo').attr('src', '<?php echo $this->basePath('/photos/') ?>' + xhttp.responseText + '?random=' + (new Date()).getTime());
 		}
 	}
 	xhttp.send(formData);
 });
 
// Enable the form
$('.profile_search_close').hide();
$('#submit_button').hide();
$('#enabler_button').click(function () {
  $('.profile_input').attr('disabled', false);
  $('.profile_search_close').show();
  $('#submit_button').show();
  $('#enabler_button').hide();
  $('.profile_input_focused').focus();
});

// Submit the form

<?php foreach ($form['inputs'] as $inputId => $property) : ?>
	<?php if ($property['type'] == 'chips') : ?>
	var <?php echo $inputId ?> = {
	<?php $first = true; foreach ($property['repository'] as $entryId => $entry) : ?>
	<?php 
	if (!$first) echo ',';
	$first = false;
	 ?>
	 	"<?php echo $entryId ?>": "<?php echo $context->localize($entry['labels'], $locale) ?>"
	<?php endforeach;?>
	};

  $('.search-<?php echo $inputId ?>-hidden').hide();

  $('#<?php echo $property['trigger'] ?>').mdb_autocomplete({
      data: <?php echo $inputId ?>
  });

  $('#<?php echo $property['trigger'] ?>').change(function () {
      var matched;
      setTimeout(function () {
	        for (id in <?php echo $inputId ?>) {
	        	if (<?php echo $inputId ?>[id] == $('#<?php echo $property['trigger'] ?>').val()) {
		        	$('#<?php echo $inputId ?>-' + id).val(1);
		        	$('#search-<?php echo $inputId ?>-' + id).show();
		        	$('#<?php echo $property['trigger'] ?>').val('');
		        	break;
	        	}
	        }
      }, 600);
  });

  $('.search-<?php echo $inputId ?>-close').click(function () {
	<?php foreach ($property['repository'] as $entryId => $entry) : ?>
  	if ($(this).attr('id').split('-')[2] == '<?php echo $entryId ?>') $('#<?php echo $inputId ?>-<?php echo $entryId ?>').val(0);
	<?php endforeach;?>
	$(this).parent().parent().hide();
  });
  <?php endif;?>
<?php endforeach;?>

<?php if ($message) : ?>
toastr.success('<?php echo $this->translate('Your request has been registered', 'ppit-core', $context->getLocale()) ?>');
<?php endif;?>

//Tooltips Initialization
$(function () {
$('[data-toggle="tooltip"]').tooltip()
})

<?php foreach ($tooltips as $itemId => $tooltip) : ?>
$('<?php echo $itemId ?>').attr('data-toggle', 'tooltip');
$('<?php echo $itemId ?>').addClass('red-tooltip');
$('<?php echo $itemId ?>').attr('data-placement', '<?php echo (array_key_exists('data-placement', $tooltip)) ? $tooltip['data-placement'] : 'right' ?>');
$('<?php echo $itemId ?>').attr('title', '<?php echo $context->localize($tooltip['title'], $locale) ?>');
<?php endforeach;?>

// Profile

function showProfile(id) {
    var xhttp = new XMLHttpRequest();
    xhttp.open('GET', '<?php echo $this->url('profile/profile') ?>/' + id, true);
    xhttp.onload = function () {
      if (xhttp.readyState == 4 && xhttp.status == 200) $('#show_profile_content').html(xhttp.responseText);
      else technicalError;

      // Add the other profile to my profile matched accounts
      $('#button_contact').unbind();
      $('#button_contact').click(function () {
        var xhttp = new XMLHttpRequest();
        xhttp.open('GET', '<?php echo $this->url('profile/contact') ?>/' + id, true);
        xhttp.onload = function () {
          if (xhttp.readyState == 4 && xhttp.status == 200) {
            showProfile(id);
          }
        };
        xhttp.send();  
      });
    };
    xhttp.send();
}

function removeProfile(account_id, request_id) {
  addRequestToBasket(request_id);
  var xhttp = new XMLHttpRequest();
  xhttp.open('GET', '<?php echo $this->url('profile/removeContact') ?>/' + account_id, true);
  xhttp.onload = function () {
    if (xhttp.readyState == 4 && xhttp.status == 200) {
      showDashboard();
    }
  };
  xhttp.send();  
  removeRequestFromBasket(request_id);
}
/*
function showDashboard() {
  var xhttp = new XMLHttpRequest();
  xhttp.open('GET', '<?php //echo $this->url('request/dashboard') ?>', true);
  xhttp.onload = function () {
    if (xhttp.readyState == 4 && xhttp.status == 200) {
      document.getElementById('requests').innerHTML = xhttp.responseText;
      $('.link_profile').click(function () {
        var id = $(this).attr('id').split('-')[1];
        showProfile(id);
        $('#modalShowProfileForm').modal('show');
      });
      $('.button_remove_contact').click(function () {
        var account_id = $(this).attr('id').split('-')[1], request_id = $(this).attr('id').split('-')[2];
        removeProfile(account_id, request_id);
      });
    }
  };
  xhttp.send();
}
*/
//showDashboard();

// Requests
/*
var mode = 'Owner';

function showList() {
  var xhttp = new XMLHttpRequest();
  xhttp.open('GET', '<?php //echo $this->url('request/list') ?>?mode=' + mode, true);
  xhttp.onload = function () {
    if (xhttp.readyState == 4 && xhttp.status == 200) {
      $('#requests').html(xhttp.responseText);

      // Connect the search engine
      $('#modeOwner').change(function () {
        mode = 'Owner';
        showList();
      });

      $('#modeContributor').change(function () {
        mode = 'Contributor';
        showList();
      });

      $('.aDetailAction').click(function () {
        var request_id = $(this).attr('id').split('-')[1];
        xhttp.open('GET', '<?php //echo $this->url('request/detailv2') ?>/' + request_id, true);
        xhttp.onload = function () {
          if (xhttp.readyState == 4 && xhttp.status == 200) {
            $('#modalRequestDetailTitle').html('<?php echo $this->translate('Request detail', 'ppit-flow', $locale) ?>');
            $('#modalRequestDetailContent').html(xhttp.responseText);
            $('#modalRequestDetailForm').modal('show');
          }
        };
        xhttp.send();
      });

      $('.aDetailAction').click(function () {
        var request_id = $(this).attr('id').split('-')[1];
        xhttp.open('GET', '<?php //echo $this->url('request/detailv2') ?>/' + request_id, true);
        xhttp.onload = function () {
          if (xhttp.readyState == 4 && xhttp.status == 200) {
            $('#modalRequestDetailTitle').html('<?php echo $this->translate('Request detail', 'ppit-flow', $locale) ?>');
            $('#modalRequestDetailContent').html(xhttp.responseText);
            $('#modalRequestDetailForm').modal('show');
          }
        };
        xhttp.send();
      });

      <?php $action = $requestContent['detail']['OwnerActions']['update'] ?>
      $('.aUpdateAction').click(function () {
        var request_id = $(this).attr('id').split('-')[1];
    	location.href = '<?php //echo $this->url('request/fill')?>/' + request_id;
      });

<?php foreach ($requestContent['detail']['OwnerActions'] as $action_id => $action) : ?>
  <?php if ($action_id == 'consultFeedback') : ?>

      $('.aOwnerAction-<?php echo $action_id ?>').click(function () {
        var request_id = $(this).attr('id').split('-')[2];
        $('#modalShowProfileTitle').html('<?php echo $context->localize($action['labels'], $locale) ?>');
        xhttp.open('GET', '<?php //echo $this->url('request/consultFeedback') ?>/' + request_id, true);
        xhttp.onload = function () {
          if (xhttp.readyState == 4 && xhttp.status == 200) {
            $('#modalShowProfileContent').html(xhttp.responseText);
            $('#modalShowProfileForm').modal('show');
          }
        };
        xhttp.send();
      });
 
  <?php else : ?>

      $('.aOwnerAction-<?php echo $action_id ?>').click(function () {
        var action = $(this).attr('id').split('-')[1];
        var request_id = $(this).attr('id').split('-')[2];
        $('#modalRequestActionTitle').html('<?php echo $context->localize($action['labels'], $locale) ?>');
        xhttp.open('GET', '<?php //echo $this->url('request/detailv2') ?>/' + request_id, true);
        xhttp.onload = function () {
          if (xhttp.readyState == 4 && xhttp.status == 200) {
            $('#modalRequestActionContent').html(xhttp.responseText);
            $('#buttonRequestAction').html('<?php echo $context->localize($action['labels'], $locale) ?>');
            $('#buttonRequestAction').unbind();
            $('#buttonRequestAction').click(function () {
              var xhttp = new XMLHttpRequest();
              xhttp.open('POST', '<?php //echo $this->url('request/'.$action_id) ?>/' + request_id, true);
              xhttp.onload = function () {
                if (xhttp.readyState == 4) {
                  if (xhttp.status == 200) {
                    toastr.success('<h4 class="text-center"><?php echo $this->translate('Your request has been registered', 'ppit-core', $context->getLocale()) ?></h4>');
                    showList();
                  }
                  else technicalError();
                }
              };
              xhttp.send();  
            });

            $('#modalRequestActionForm').modal('show');
          }
        };
        xhttp.send();
      });

  <?php endif;?>
<?php endforeach;?>

      $('.aMatchingDetailAction').click(function () {
        var request_id = $(this).attr('id').split('-')[1];
        var account_id = $(this).attr('id').split('-')[2];
        var xhttp = new XMLHttpRequest();
        xhttp.open('GET', '<?php //echo $this->url('profile/detail') ?>/' + request_id + '/' + account_id, true);
        xhttp.onload = function () {
          if (xhttp.readyState == 4 && xhttp.status == 200) {
            $('#modalShowProfileTitle').html('<?php echo $this->translate('Profile', 'ppit-flow', $locale) ?>');
            $('#modalShowProfileContent').html(xhttp.responseText);
            $('.dataProtected').hide();
            $('#modalShowProfileForm').modal('show');
          }
        };
        xhttp.send();
      });

      $('.aMatchingSearchAction').click(function () {
        var id = $(this).attr('id').split('-')[1];
        var xhttp = new XMLHttpRequest();
        xhttp.open('GET', '<?php echo $this->url('profile/list') ?>/' + id, true);
        xhttp.onload = function () {
          if (xhttp.readyState == 4 && xhttp.status == 200) {
            $('#modalShowProfileTitle').html('<?php echo $this->translate('Profile', 'ppit-flow', $locale) ?>');
            $('#modalShowProfileContent').html(xhttp.responseText);
            $('.dataProtected').hide();
            $('.buttonContact').click(function () {
              var account_id = $(this).attr('id').split('-')[1];
              var xhttp = new XMLHttpRequest();
              xhttp.open('POST', '<?php //echo $this->url('request/contact') ?>/' + id + '?accounts=' + account_id, true);
              xhttp.onload = function () {
                if (xhttp.readyState == 4) {
                  if (xhttp.status == 200) {
                      showList();
                  }
                  else technicalError;
                }
              };
              xhttp.send();
            });
            $('#modalShowProfileForm').modal('show');
          }
        };
        xhttp.send();
      });

<?php foreach ($requestContent['detail']['MatchingActions'] as $action_id => $action) : ?>
	
  <?php if ($action_id == 'feedback') : ?>
      $('.aMatchingAction-<?php echo $action_id ?>').click(function () {
        var request_id = $(this).attr('id').split('-')[2];
        var account_id = $(this).attr('id').split('-')[3];
        location.href = '<?php //echo $this->url('request/feedback')?>/' + request_id + '?contributor=' + account_id;
      });

  <?php else : ?>
      $('.aMatchingAction-<?php echo $action_id ?>').click(function () {
        var action = $(this).attr('id').split('-')[1];
        var request_id = $(this).attr('id').split('-')[2];
        var account_id = $(this).attr('id').split('-')[3];
        $('#modalRequestActionTitle').html('<?php echo $context->localize($action['labels'], $locale) ?>');
        xhttp.open('GET', '<?php echo $this->url('profile/detail') ?>/' + request_id + '/' + account_id + '?actions=' + action, true);
        xhttp.onload = function () {
          if (xhttp.readyState == 4 && xhttp.status == 200) {
            $('#modalRequestActionContent').html(xhttp.responseText);
            $('#buttonRequestAction').html('<?php echo $context->localize($action['labels'], $locale) ?>');
            $('#buttonRequestAction').unbind();
            $('#buttonRequestAction').click(function () {
              var xhttp = new XMLHttpRequest();
              xhttp.open('POST', '<?php //echo $this->url('request/'.$action_id) ?>/' + request_id + '?accounts=' + account_id, true);
              xhttp.onload = function () {
                if (xhttp.readyState == 4) {
                  if (xhttp.status == 200) {
                    toastr.success('<h4 class="text-center"><?php echo $this->translate('Your request has been registered', 'ppit-core', $context->getLocale()) ?></h4>');
                    showList();
                  }
                  else technicalError();
                }
              };
              xhttp.send();  
            });

            $('#modalRequestActionForm').modal('show');
          }
        };
        xhttp.send();
      });
  <?php endif;?>
<?php endforeach;?>

<?php foreach ($requestContent['detail']['ContributorActions'] as $action_id => $action) : ?>

	<?php if ($action_id == 'feedback') : ?>
      $('.aContributorAction-<?php echo $action_id ?>').click(function () {
        var request_id = $(this).attr('id').split('-')[2];
        var account_id = $(this).attr('id').split('-')[3];
        location.href = '<?php //echo $this->url('request/feedback')?>/' + request_id + '?contributor=' + account_id;
      });

    <?php elseif ($action_id == 'consultFeedback') : ?>

      $('.aContributorAction-<?php echo $action_id ?>').click(function () {
        var request_id = $(this).attr('id').split('-')[2];
        $('#modalShowProfileTitle').html('<?php echo $context->localize($action['labels'], $locale) ?>');
        xhttp.open('GET', '<?php //echo $this->url('request/consultFeedback') ?>/' + request_id, true);
        xhttp.onload = function () {
          if (xhttp.readyState == 4 && xhttp.status == 200) {
            $('#modalShowProfileContent').html(xhttp.responseText);
            $('#modalShowProfileForm').modal('show');
          }
        };
        xhttp.send();
      });

  	<?php else : ?>
      $('.aContributorAction-<?php echo $action_id ?>').click(function () {
          var action = $(this).attr('id').split('-')[1];
          var request_id = $(this).attr('id').split('-')[2];
          $('#modalRequestActionTitle').html('<?php echo $context->localize($action['labels'], $locale) ?>');
          xhttp.open('GET', '<?php //echo $this->url('request/detailv2') ?>/' + request_id, true);
          xhttp.onload = function () {
            if (xhttp.readyState == 4 && xhttp.status == 200) {
              $('#modalRequestActionContent').html(xhttp.responseText);
              $('#buttonRequestAction').html('<?php echo $context->localize($action['labels'], $locale) ?>');
              $('#buttonRequestAction').unbind();
              $('#buttonRequestAction').click(function () {
                var xhttp = new XMLHttpRequest();
                xhttp.open('POST', '<?php //echo $this->url('request/'.$action_id) ?>/' + request_id, true);
                xhttp.onload = function () {
                  if (xhttp.readyState == 4) {
                    if (xhttp.status == 200) {
                      toastr.success('<h4 class="text-center"><?php echo $this->translate('Your request has been registered', 'ppit-core', $context->getLocale()) ?></h4>');
                      showList();
                    }
                    else technicalError();
                  }
                };
                xhttp.send();  
              });

              $('#modalRequestActionForm').modal('show');
            }
          };
          xhttp.send();
      });
    <?php endif;?>
<?php endforeach;?>

    }
  };
  xhttp.send();
}

showList();
*/
function technicalError() {
  toastr.error('<h4 class="text-center"><?php echo $this->translate('A technical error has occured. PLease try again later', 'ppit-core', $context->getLocale()) ?></h4>');  
}
</script>
