<!DOCTYPE html>
<html lang="en">

<head>
<?php if (array_key_exists('analytics-id', $content['header'])) : ?>
<!-- Google Analytics -->
<script>
(function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','https://www.google-analytics.com/analytics.js','ga');

ga('create', '<?php echo $content['header']['analytics-id']?>', 'auto');
ga('send', 'pageview');
</script>
<!-- End Google Analytics -->
<?php endif;?>

    <title><?php echo $context->localize($content['header']['title'], $locale) ?></title>
    <meta charset="utf-8">
	<meta name="description" content="<?php echo $context->localize($content['header']['description'], $locale) ?>">
	<meta name="robots" content="index, follow">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <!-- Font Awesome -->
	<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.0.10/css/all.css" integrity="sha384-+d0P83n9kaQMCwj8F4RJB66tzIwOKmrdb46+porD/OvrJ+37WqIM7UoBtwHO6Nlg" crossorigin="anonymous">    <!-- Bootstrap core CSS -->
    <link href="<?php echo $this->basePath('MDB Pro/css/bootstrap.min.css" rel="stylesheet') ?>">
    <!-- Material Design Bootstrap -->
    <link href="<?php echo $this->basePath('MDB Pro/css/mdb.min.css" rel="stylesheet') ?>">
    <!-- Your custom styles (optional) -->
    <link href="<?php echo $this->basePath('MDB Pro/css/style.css" rel="stylesheet') ?>">

    <link rel="stylesheet" href="<?php echo $this->basePath('medium-editor-master/dist/css/medium-editor.css') ?>">
    <link rel="stylesheet" href="<?php echo $this->basePath('medium-editor-master/dist/css/themes/default.css" id="medium-editor-theme') ?>">

<style>
html,
body,
header,
#intro {
    height: 65%;
}

#intro {
    background: url("<?php echo $this->basePath($content['header']['background_image']['src']) ?>") no-repeat ;
    -webkit-background-size: cover;
    -moz-background-size: cover;
    -o-background-size: cover;
    background-size: cover;
}

@include media-breakpoint-up(sm) {
  html {
    font-size: 16px;
  }
}

@include media-breakpoint-up(md) {
  html {
    font-size: 20px;
  }
}

@include media-breakpoint-up(lg) {
  html {
    font-size: 28px;
  }
}
</style>
</head>

<body>

    <!--Main Navigation-->
    <header>

        <!--Navbar-->
        <nav class="navbar navbar-expand-lg navbar-dark fixed-top scrolling-navbar navbar-transparent">
            <div class="container">

                <!-- Navbar brand -->
				<a href="<?php echo $this->url($content['header']['logo']['href'], $content['header']['logo']['params']) ?>" class="navbar-brand">
					<img 
						src="<?php echo $this->basePath($content['header']['logo']['src']) ?>"
						<?php if (array_key_exists('height', $content['header']['logo'])) echo 'height="'.$content['header']['logo']['height'].'"' ?>
						<?php if (array_key_exists('width', $content['header']['logo'])) echo 'width="'.$content['header']['logo']['width'].'"' ?>
						alt="<?php echo $content['header']['logo']['alt'] ?>"
					/>
				</a>

                <!-- Collapse button -->
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav" aria-controls="basicExampleNav"
                    aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>

                <!-- Collapsible content -->
                <div class="collapse navbar-collapse" id="basicExampleNav">
                    
                    <!-- Links -->
                    <ul class="navbar-nav mr-auto">
                        <li class="nav-item">
                            <a class="nav-link" href="<?php echo $this->url($content['header']['logo']['href'], $content['header']['logo']['params']) ?>"><?php echo $this->translate('Home', 'ppit-core', $context->getLocale()) ?></a>
                        </li>
                        <li class="nav-item">
<?php if ($locale == 'fr_FR') : ?>
							<a class="nav-link" href="<?php echo $this->url('profile/template2', ['id' => $id]) ?>?hash=<?php echo $token ?>&locale=en_US">EN</a>
<?php else : ?>
							<a class="nav-link" href="<?php echo $this->url('profile/template2', ['id' => $id]) ?>?hash=<?php echo $token ?>&locale=fr_FR">FR</a>
<?php endif;?>
                        </li>
                    </ul>
                    <!-- Links -->
                    
                    <!-- Social Icon  -->
                    <ul class="navbar-nav nav-flex-icons">
                    </ul>
                                            
                </div>
                <!-- Collapsible content -->

            </div>
        </nav>
        <!--/.Navbar-->    
 
<!--Mask-->
<div id="intro" class="view h-100"> 
	<div class="d-block h-100 w-lg-100 <?php echo $content['header']['background_image']['mask'] ?>">
    	<div class="full-bg-img flex-center">
            <div class="col-md-12 justify-content-center text-center">
<?php if ($message || $error) : ?>
					<h3 class="h3-responsive white-text my-4">
						<?php echo $this->translate('Your request has been registered', 'ppit-core', $context->getLocale()) ?>.<br>Nous vous remercions de votre confiance.
					</h3>
<?php else : ?>
	<?php foreach ($content['intro'] as $paragraphId => $paragraph) : ?>
		<?php if (array_key_exists('a', $paragraph)) : ?>
					<a 
						href="<?php echo $this->url('landing/template2') ?><?php echo $paragraph['a']['href']?>" 
						<?php if (array_key_exists('class', $paragraph['a'])) echo 'class="'.$paragraph['a']['class'].'"' ?>
						<?php if (array_key_exists('id', $paragraph['a'])) echo 'id="'.$paragraph['a']['id'].'"' ?>
					>
		<?php elseif (array_key_exists('button', $paragraph)) : ?>
					<button type="button" 
						<?php if (array_key_exists('class', $paragraph['button'])) echo 'class="'.$paragraph['button']['class'].'"' ?>
						<?php if (array_key_exists('id', $paragraph['button'])) echo 'id="'.$paragraph['button']['id'].'"' ?>
					>
		<?php else : ?>
					<<?php echo $paragraph['type']?> class="editable <?php if (array_key_exists('class', $paragraph)) echo $paragraph['class'] ?>" id="<?php echo $paragraphId ?>/text<?php if (array_key_exists('text', $paragraph)) echo '/'.$context->getLocaleFor($paragraph['text']) ?>">
		<?php endif;?>
		<?php if (array_key_exists('text', $paragraph)) : ?>
			<?php echo $context->localize($paragraph['text'], $locale) ?>
		<?php endif;?>
		<?php if (array_key_exists('a', $paragraph)) : ?>
					</a>
		<?php elseif (array_key_exists('button', $paragraph)) : ?>
					</button>
		<?php else : ?>
					</<?php echo $paragraph['type']?>>
		<?php endif;?>
	<?php endforeach;?>
<?php endif;?>
	        </div>
        </div>
    </div>
</div>
<!--/.Mask-->
            
    </header>
    <!--Main Navigation-->

    <!--Main layout-->
    <main>
    
        <div class="container">
           
            <!--Section: Blog v.3-->
            <section class="section text-center text-lg-left wow fadeIn" data-wow-delay="0.3s">
				<div>&nbsp;</div>

 <?php foreach ($content['intro'] as $paragraph) : ?>
		<?php if (array_key_exists('a', $paragraph)) : ?>
					<a 
						href="<?php echo $paragraph['a']['href']?>" 
						<?php if (array_key_exists('class', $paragraph['a'])) echo 'class="'.$paragraph['a']['class'].'"' ?>
						<?php if (array_key_exists('id', $paragraph['a'])) echo 'id="'.$paragraph['a']['id'].'"' ?>
					>
		<?php elseif (array_key_exists('button', $paragraph)) : ?>
					<button type="button" 
						<?php if (array_key_exists('class', $paragraph['button'])) echo 'class="'.$paragraph['button']['class'].'"' ?>
						<?php if (array_key_exists('id', $paragraph['button'])) echo 'id="'.$paragraph['button']['id'].'"' ?>
					>
		<?php else : ?>
					<<?php echo $paragraph['type']?> <?php if (array_key_exists('class', $paragraph)) echo 'class="'.$paragraph['class'].'"' ?>>
		<?php endif;?>
		<?php if (array_key_exists('text', $paragraph)) : ?>
			<?php echo $context->localize($paragraph['text'], $locale) ?>
		<?php endif;?>
		<?php if (array_key_exists('a', $paragraph)) : ?>
					</a>
		<?php elseif (array_key_exists('button', $paragraph)) : ?>
					</button>
		<?php else : ?>
					</<?php echo $paragraph['type']?>>
		<?php endif;?>
<?php endforeach;?>

                <!--Grid row-->
                <div class="row">

                    <!--Grid column-->
                    <div class="col-lg-4 mb-4">
<!-- Card -->
<div class="card testimonial-card">

    <!-- Bacground color -->
    <div class="card-up indigo lighten-1">
    </div>

    <!-- Avatar -->
    <div class="avatar mx-auto white"><img src="<?php echo $this->basePath('/photos/no-photo.png')?>" class="rounded-circle">
    </div>

    <div class="card-body">
       <section class="section feature-box wow fadeIn" data-wow-delay="0.3s">
       		<p class="section-description"><strong><span class="editable"><?php echo $context->localize($content['card']['last_name']['value']) ?></span>, <span class="editable"><?php echo $context->localize($content['card']['first_name']['value']) ?></span></strong></p>
       		<p class="section-description"><span class="editable"><?php echo $context->localize($content['card']['position']['value']) ?></span></p>
       		<hr/>
       		<p class="section-description"><strong><span class="editable"><?php echo $context->localize($content['card']['location']['value']) ?></span></strong></p>
       		<p class="section-description"><span class="editable"><?php echo $context->localize($content['card']['service']['value']) ?></span></p>
      </section>
	</div>
</div>
					</div>

                    <!--Grid column-->
                    <div class="col-lg-7 mb-4">
<?php foreach ($content['features'] as $featureId => $feature) : ?>
                        <h6 class="<?php echo $feature['class'] ?>"><i class="<?php echo $feature['i_class'] ?>"></i><strong> <?php echo $context->localize($feature['title']) ?></strong></h6>
	<?php foreach ($feature['value'] as $paragraphId => $paragraph) : ?>
						<<?php echo $paragraph['type']?> class="editable <?php if (array_key_exists('class', $paragraph)) echo $paragraph['class'] ?>" id="<?php echo $paragraphId ?>/text<?php if (array_key_exists('text', $paragraph)) echo '/'.$context->getLocaleFor($paragraph['text']) ?>">
		<?php if (array_key_exists('text', $paragraph)) : ?>
						<?php echo $context->localize($paragraph['text'], $locale) ?>
		<?php endif;?>
						</<?php echo $paragraph['type']?>>
	<?php endforeach;?>
<?php endforeach;?>
                    </div>
                    <!--Grid column-->

                </div>
                <!--Grid row-->

            </section>
            <!--Section: Blog v.2-->
        
        </div>
        <div class="row">
        
<?php foreach ($content['form']['introduction'] as $paragraph) : ?>
		<?php if (array_key_exists('a', $paragraph)) : ?>
					<a 
						href="<?php echo $paragraph['a']['href']?>" 
						<?php if (array_key_exists('class', $paragraph['a'])) echo 'class="'.$paragraph['a']['class'].'"' ?>
						<?php if (array_key_exists('id', $paragraph['a'])) echo 'id="'.$paragraph['a']['id'].'"' ?>
					>
		<?php elseif (array_key_exists('button', $paragraph)) : ?>
					<button type="button" 
						<?php if (array_key_exists('class', $paragraph['button'])) echo 'class="'.$paragraph['button']['class'].'"' ?>
						<?php if (array_key_exists('id', $paragraph['button'])) echo 'id="'.$paragraph['button']['id'].'"' ?>
					>
		<?php else : ?>
					<<?php echo $paragraph['type']?> <?php if (array_key_exists('class', $paragraph)) echo 'class="'.$paragraph['class'].'"' ?>>
		<?php endif;?>
		<?php if (array_key_exists('text', $paragraph)) : ?>
			<?php echo $context->localize($paragraph['text'], $locale) ?>
		<?php endif;?>
		<?php if (array_key_exists('a', $paragraph)) : ?>
					</a>
		<?php elseif (array_key_exists('button', $paragraph)) : ?>
					</button>
		<?php else : ?>
					</<?php echo $paragraph['type']?>>
		<?php endif;?>
<?php endforeach;?>
		</div>

   <!--Footer-->
    <footer class="page-footer center-on-small-only mt-5">

        <!--Footer Links-->
        <div class="container">
            <div class="row">

                <!--First column-->
                <div class="col-md-3">
                    <h5 class="title">Ressources </h5>
                </div>
                <!--/.First column-->

                <hr class="w-100 clearfix d-md-none">

                <!--Second column-->
                <div class="col-md-2 ml-auto">
                    <ul>
                        <li><a href="#!">Blog</a></li>
                    </ul>
                </div>
                <!--/.Second column-->

            </div>
        </div>

        <!--Copyright-->
        <div class="footer-copyright">
            <div class="container-fluid">
                © 2018 Copyright: <a href="http://www.flowux.io"> Flow UX </a>

            </div>
        </div>
        <!--/.Copyright-->

    </footer>
    </main>
    <!--Main layout-->
</body>
    	
    <!-- SCRIPTS -->
    <!-- Font Awesome -->
    <!-- JQuery -->
    <script type="text/javascript" src="<?php echo $this->basePath('MDB Pro/js/jquery-3.2.1.min.js') ?>"></script>
    <!-- Bootstrap tooltips -->
    <script type="text/javascript" src="<?php echo $this->basePath('MDB Pro/js/popper.min.js') ?>"></script>
    <!-- Bootstrap core JavaScript -->
    <script type="text/javascript" src="<?php echo $this->basePath('MDB Pro/js/bootstrap.min.js') ?>"></script>
    <!-- MDB core JavaScript -->
    <script type="text/javascript" src="<?php echo $this->basePath('MDB Pro/js/mdb.min.js') ?>"></script>

<script type="text/javascript">
// Material Select Initialization
new WOW().init();
$(document).ready(function() {
   $('.mdb-select').material_select();
});

<?php if ($message && array_key_exists('analytics', $content['header'])) : ?>
ga('send', 'event', '<?php echo (array_key_exists('campaign', $content['header'])) ? $content['header']['campaign'] : $place_identifier ?>', 'submit', 'landing_template2#survey', 1);
<?php endif;?>

$('#a_survey').click(function () {
<?php if (array_key_exists('analytics', $content['header'])) : ?>
	ga('send', 'event', '<?php echo (array_key_exists('campaign', $content['header'])) ? $content['header']['campaign'] : $place_identifier ?>', 'click', 'landing_template2#survey', 1);
<?php endif;?>
	$(location).attr('href', '#descr');
});
</script>
<?php //if ($context->hasRole('sales_manager')) : ?>
<script src="<?php echo $this->basePath('medium-editor-master/dist/js/medium-editor.js') ?>"></script>
<script>
	//Returns a function, that, as long as it continues to be invoked, will not
	//be triggered. The function will be called after it stops being called for
	//N milliseconds. If `immediate` is passed, trigger the function on the
	//leading edge, instead of the trailing.
	function debounce(func, wait, immediate) {
		var timeout;
		return function() {
			var context = this, args = arguments;
			var later = function() {
				timeout = null;
				if (!immediate) func.apply(context, args);
			};
			var callNow = immediate && !timeout;
			clearTimeout(timeout);
			timeout = setTimeout(later, wait);
			if (callNow) func.apply(context, args);
		};
	};
	var editor = new MediumEditor('.editable', {
        buttonLabels: 'fontawesome'
    });
    function triggerAutoSave(event, editable) {
    	var xhttp = new XMLHttpRequest();
    	xhttp.open("POST", '<?php echo $this->url('config/v1', ['id' => $id.'_profile']) ?>', true);
    	xhttp.onreadystatechange = function() {
    		if (xhttp.readyState == 4 && xhttp.status == 200) {
    		}
    	}
        var content = { content: {} };
        content.content['intro/' + editable.id] = editable.innerHTML;
    	xhttp.send(JSON.stringify(content));
    }
    var throttledAutoSave = debounce(triggerAutoSave, 1000);
    editor.subscribe('editableInput', throttledAutoSave);
</script>
<?php //endif;?>
</html>
